import { Examen, ExamenReport } from '@examenkompas/data';

export const vaknaam = 'natuur- en scheikunde 1';
export const niveau = 'VMBO_GL-TL';
export const report = {
  eindCijfer: 7.1,
  volledigBeantwoord: true,
  domeinscores: [
    {
      domein: {
        titel: 'Informatieoverdracht (B1)',
        titelHtml:
          '<a href="https://zoeken.wikiwijs.nl/zoekopdracht/5004560">Informatieoverdracht (B1)</a>',
      },
      percentageGoed: 0.82,
      percentageGoedPopulatieLaag: 0.36,
      percentageGoedPopulatieHoog: 0.78,
      volledigBeantwoord: true,
      voldoendeScorepunten: true,
    },
    {
      domein: {
        titel: 'Medische beeldvorming (B2)',
        titelHtml:
          '<a href="https://zoeken.wikiwijs.nl/zoekopdracht/5004561">Medische beeldvorming (B2)</a>',
      },
      percentageGoed: 0.81,
      percentageGoedPopulatieLaag: 0.33,
      percentageGoedPopulatieHoog: 0.7,
      volledigBeantwoord: true,
      voldoendeScorepunten: true,
    },
    {
      domein: {
        titel: 'Kracht en beweging (C1)',
        titelHtml:
          '<a href="https://zoeken.wikiwijs.nl/zoekopdracht/5004563">Kracht en beweging (C1)</a>',
      },
      percentageGoed: 0.64,
      percentageGoedPopulatieLaag: 0.5,
      percentageGoedPopulatieHoog: 0.85,
      volledigBeantwoord: true,
      voldoendeScorepunten: true,
    },
    {
      domein: {
        titel: 'Energieomzettingen (C2)',
        titelHtml:
          '<a href="https://zoeken.wikiwijs.nl/zoekopdracht/5004757">Energieomzettingen (C2)</a>',
      },
      percentageGoed: 0.73,
      percentageGoedPopulatieLaag: 0.46,
      percentageGoedPopulatieHoog: 0.84,
      volledigBeantwoord: true,
      voldoendeScorepunten: true,
    },
    {
      domein: {
        titel: 'Eigenschappen van stoffen en materialen (D1)',
        titelHtml:
          '<a href="https://zoeken.wikiwijs.nl/zoekopdracht/5004683">Eigenschappen van stoffen en materialen (D1)</a>',
      },
      percentageGoed: 0.75,
      percentageGoedPopulatieLaag: 0.31,
      percentageGoedPopulatieHoog: 0.73,
      volledigBeantwoord: true,
      voldoendeScorepunten: true,
    },
    {
      domein: {
        titel: 'Aarde en heelal (E)',
        titelHtml:
          '<a href="https://zoeken.wikiwijs.nl/zoekopdracht/5004749">Aarde en heelal (E)</a>',
      },
      percentageGoed: 0.83,
      percentageGoedPopulatieLaag: 0.19,
      percentageGoedPopulatieHoog: 0.7,
      volledigBeantwoord: true,
      voldoendeScorepunten: false,
    },
    {
      domein: {
        titel: 'Gebruik van elektriciteit (G1)',
        titelHtml:
          '<a href="https://zoeken.wikiwijs.nl/zoekopdracht/5004752">Gebruik van elektriciteit (G1)</a>',
      },
      percentageGoed: 0.82,
      percentageGoedPopulatieLaag: 0.46,
      percentageGoedPopulatieHoog: 0.8,
      volledigBeantwoord: true,
      voldoendeScorepunten: true,
    },
  ],
} as ExamenReport;
export const examen: Examen = {
  examenId: 17199,
  tijdvak: 1,
  opleidingsniveau: 0,
  leerweg: 2,
  vakcode: '0173',
  tekstboekje: '',
  vaknaam: 'natuur- en scheikunde 1',
  isPilot: false,
  jaar: 2017,
  opgavenboekje: 'https://www2.cito.nl/vo/ex2017/GT-0173-a-17-1-o.pdf',
  correctievoorschrift: 'https://www2.cito.nl/vo/ex2017/GT-0173-a-17-1-c.pdf',
  uitwerkbijlage: 'https://www2.cito.nl/vo/ex2017/GT-0173-a-17-1-u.pdf',
  opgaven: [
    {
      titel: 'Thee zetten',
      items: [
        {
          code: '5651',
          titel: null,
          volgnummer: 1,
          maxscore: 2,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Verbranden en verwarmen (K6)'],
        },
        {
          code: '5652',
          titel: null,
          volgnummer: 2,
          maxscore: 2,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Stoffen en materialen (K4)'],
        },
        {
          code: '5653',
          titel: null,
          volgnummer: 3,
          maxscore: 1,
          sleutel: 'A',
          aantalAlternatieven: 3,
          calamiteit: false,
          domeinen: ['Stoffen en materialen (K4)'],
        },
        {
          code: '5654',
          titel: null,
          volgnummer: 4,
          maxscore: 2,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Verbranden en verwarmen (K6)'],
        },
      ],
    },
    {
      titel: 'Carbidschieten',
      items: [
        {
          code: '5655',
          titel: null,
          volgnummer: 5,
          maxscore: 2,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Stoffen en materialen (K4)'],
        },
        {
          code: '5656',
          titel: null,
          volgnummer: 6,
          maxscore: 1,
          sleutel: 'A',
          aantalAlternatieven: 3,
          calamiteit: false,
          domeinen: ['Kracht en veiligheid (K9)'],
        },
        {
          code: '5657',
          titel: null,
          volgnummer: 7,
          maxscore: 2,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Stoffen en materialen (K4)'],
        },
        {
          code: '5658',
          titel: null,
          volgnummer: 8,
          maxscore: 1,
          sleutel: 'A',
          aantalAlternatieven: 3,
          calamiteit: false,
          domeinen: ['Verbranden en verwarmen (K6)'],
        },
        {
          code: '5659',
          titel: null,
          volgnummer: 9,
          maxscore: 1,
          sleutel: 'C',
          aantalAlternatieven: 4,
          calamiteit: false,
          domeinen: ['Geluid (K8)'],
        },
        {
          code: '5660',
          titel: null,
          volgnummer: 10,
          maxscore: 1,
          sleutel: 'B',
          aantalAlternatieven: 4,
          calamiteit: false,
          domeinen: ['Stoffen en materialen (K4)'],
        },
        {
          code: '5661',
          titel: null,
          volgnummer: 11,
          maxscore: 1,
          sleutel: 'B',
          aantalAlternatieven: 3,
          calamiteit: false,
          domeinen: ['Stoffen en materialen (K4)'],
        },
      ],
    },
    {
      titel: 'Buiklanding',
      items: [
        {
          code: '5662',
          titel: null,
          volgnummer: 12,
          maxscore: 1,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Verbranden en verwarmen (K6)'],
        },
        {
          code: '5663',
          titel: null,
          volgnummer: 13,
          maxscore: 2,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Kracht en veiligheid (K9)'],
        },
        {
          code: '5664',
          titel: null,
          volgnummer: 14,
          maxscore: 2,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: [],
        },
        {
          code: '5665',
          titel: null,
          volgnummer: 15,
          maxscore: 3,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: [],
        },
        {
          code: '5666',
          titel: null,
          volgnummer: 16,
          maxscore: 2,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: [],
        },
        {
          code: '5667',
          titel: null,
          volgnummer: 17,
          maxscore: 2,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Kracht en veiligheid (K9)'],
        },
      ],
    },
    {
      titel: 'Vogelbescherming',
      items: [
        {
          code: '5668',
          titel: null,
          volgnummer: 18,
          maxscore: 2,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Elektrische energie (K5)'],
        },
        {
          code: '5669',
          titel: null,
          volgnummer: 19,
          maxscore: 1,
          sleutel: 'C',
          aantalAlternatieven: 4,
          calamiteit: false,
          domeinen: ['Elektrische energie (K5)'],
        },
        {
          code: '5670',
          titel: null,
          volgnummer: 20,
          maxscore: 1,
          sleutel: 'B',
          aantalAlternatieven: 3,
          calamiteit: false,
          domeinen: ['Geluid (K8)'],
        },
        {
          code: '5671',
          titel: null,
          volgnummer: 21,
          maxscore: 3,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Geluid (K8)'],
        },
        {
          code: '5672',
          titel: null,
          volgnummer: 22,
          maxscore: 2,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Geluid (K8)'],
        },
        {
          code: '5673',
          titel: null,
          volgnummer: 23,
          maxscore: 2,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Geluid (K8)'],
        },
        {
          code: '5674',
          titel: null,
          volgnummer: 24,
          maxscore: 2,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Elektrische energie (K5)'],
        },
      ],
    },
    {
      titel: 'Dalende spanning',
      items: [
        {
          code: '5675',
          titel: null,
          volgnummer: 25,
          maxscore: 2,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Elektrische energie (K5)'],
        },
        {
          code: '5676',
          titel: null,
          volgnummer: 26,
          maxscore: 2,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Elektrische energie (K5)'],
        },
        {
          code: '5677',
          titel: null,
          volgnummer: 27,
          maxscore: 2,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Elektrische energie (K5)'],
        },
        {
          code: '5678',
          titel: null,
          volgnummer: 28,
          maxscore: 1,
          sleutel: 'C',
          aantalAlternatieven: 3,
          calamiteit: false,
          domeinen: ['Elektrische energie (K5)'],
        },
        {
          code: '5679',
          titel: null,
          volgnummer: 29,
          maxscore: 2,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Elektrische energie (K5)'],
        },
        {
          code: '5680',
          titel: null,
          volgnummer: 30,
          maxscore: 1,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Verbranden en verwarmen (K6)'],
        },
        {
          code: '5681',
          titel: null,
          volgnummer: 31,
          maxscore: 2,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Verbranden en verwarmen (K6)'],
        },
      ],
    },
    {
      titel: 'Happy birds',
      items: [
        {
          code: '5682',
          titel: null,
          volgnummer: 32,
          maxscore: 2,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Stoffen en materialen (K4)'],
        },
        {
          code: '5683',
          titel: null,
          volgnummer: 33,
          maxscore: 1,
          sleutel: 'C',
          aantalAlternatieven: 3,
          calamiteit: false,
          domeinen: ['Stoffen en materialen (K4)'],
        },
        {
          code: '5684',
          titel: null,
          volgnummer: 34,
          maxscore: 1,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Stoffen en materialen (K4)'],
        },
        {
          code: '5685',
          titel: null,
          volgnummer: 35,
          maxscore: 3,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: [],
        },
      ],
    },
    {
      titel: 'Black box',
      items: [
        {
          code: '5686',
          titel: null,
          volgnummer: 36,
          maxscore: 2,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Elektrische energie (K5)'],
        },
        {
          code: '5687',
          titel: null,
          volgnummer: 37,
          maxscore: 1,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Elektrische energie (K5)'],
        },
        {
          code: '5688',
          titel: null,
          volgnummer: 38,
          maxscore: 2,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Elektrische energie (K5)'],
        },
        {
          code: '5689',
          titel: null,
          volgnummer: 39,
          maxscore: 2,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Elektrische energie (K5)'],
        },
      ],
    },
    {
      titel: 'Autotest',
      items: [
        {
          code: '5690',
          titel: null,
          volgnummer: 40,
          maxscore: 3,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Kracht en veiligheid (K9)'],
        },
        {
          code: '5691',
          titel: null,
          volgnummer: 41,
          maxscore: 1,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Kracht en veiligheid (K9)'],
        },
        {
          code: '5692',
          titel: null,
          volgnummer: 42,
          maxscore: 1,
          sleutel: 'B',
          aantalAlternatieven: 3,
          calamiteit: false,
          domeinen: [],
        },
        {
          code: '5693',
          titel: null,
          volgnummer: 43,
          maxscore: 1,
          sleutel: 'C',
          aantalAlternatieven: 3,
          calamiteit: false,
          domeinen: ['Kracht en veiligheid (K9)'],
        },
        {
          code: '5694',
          titel: null,
          volgnummer: 44,
          maxscore: 3,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: [],
        },
      ],
    },
  ],
  domeinen: [
    {
      titel: 'Informatieoverdracht (B1)',
      titelHtml:
        '<a href="https://zoeken.wikiwijs.nl/zoekopdracht/5004560">Informatieoverdracht (B1)</a>',
    },
    {
      titel: 'Medische beeldvorming (B2)',
      titelHtml:
        '<a href="https://zoeken.wikiwijs.nl/zoekopdracht/5004561">Medische beeldvorming (B2)</a>',
    },
    {
      titel: 'Kracht en beweging (C1)',
      titelHtml:
        '<a href="https://zoeken.wikiwijs.nl/zoekopdracht/5004563">Kracht en beweging (C1)</a>',
    },
    {
      titel: 'Energieomzettingen (C2)',
      titelHtml:
        '<a href="https://zoeken.wikiwijs.nl/zoekopdracht/5004757">Energieomzettingen (C2)</a>',
    },
    {
      titel: 'Eigenschappen van stoffen en materialen (D1)',
      titelHtml:
        '<a href="https://zoeken.wikiwijs.nl/zoekopdracht/5004683">Eigenschappen van stoffen en materialen (D1)</a>',
    },
    {
      titel: 'Aarde en heelal (E)',
      titelHtml:
        '<a href="https://zoeken.wikiwijs.nl/zoekopdracht/5004749">Aarde en heelal (E)</a>',
    },
    {
      titel: 'Gebruik van elektriciteit (G1)',
      titelHtml:
        '<a href="https://zoeken.wikiwijs.nl/zoekopdracht/5004752">Gebruik van elektriciteit (G1)</a>',
    },
  ],
};
