import { Examen, ExamenReport } from '@examenkompas/data';

export const report = {
  eindCijfer: 7.1,
  volledigBeantwoord: true,
  domeinscores: [
    {
      domein: {
        titel: 'Informatieoverdracht (B1)',
        titelHtml:
          '<a  target="_blank" rel="noreferrer"  href="https://zoeken.wikiwijs.nl/zoekopdracht/5004560">Informatieoverdracht (B1)</a>',
      },
      percentageGoed: 0.82,
      percentageGoedPopulatieLaag: 0.36,
      percentageGoedPopulatieHoog: 0.78,
      volledigBeantwoord: true,
      voldoendeScorepunten: true,
    },
    {
      domein: {
        titel: 'Medische beeldvorming (B2)',
        titelHtml:
          '<a  target="_blank" rel="noreferrer"  href="https://zoeken.wikiwijs.nl/zoekopdracht/5004561">Medische beeldvorming (B2)</a>',
      },
      percentageGoed: 0.81,
      percentageGoedPopulatieLaag: 0.33,
      percentageGoedPopulatieHoog: 0.7,
      volledigBeantwoord: true,
      voldoendeScorepunten: true,
    },
    {
      domein: {
        titel: 'Kracht en beweging (C1)',
        titelHtml:
          '<a  target="_blank" rel="noreferrer"  href="https://zoeken.wikiwijs.nl/zoekopdracht/5004563">Kracht en beweging (C1)</a>',
      },
      percentageGoed: 0.64,
      percentageGoedPopulatieLaag: 0.5,
      percentageGoedPopulatieHoog: 0.85,
      volledigBeantwoord: true,
      voldoendeScorepunten: true,
    },
    {
      domein: {
        titel: 'Energieomzettingen (C2)',
        titelHtml:
          '<a  target="_blank" rel="noreferrer"  href="https://zoeken.wikiwijs.nl/zoekopdracht/5004757">Energieomzettingen (C2)</a>',
      },
      percentageGoed: 0.73,
      percentageGoedPopulatieLaag: 0.46,
      percentageGoedPopulatieHoog: 0.84,
      volledigBeantwoord: true,
      voldoendeScorepunten: true,
    },
    {
      domein: {
        titel: 'Eigenschappen van stoffen en materialen (D1)',
        titelHtml:
          '<a  target="_blank" rel="noreferrer"  href="https://zoeken.wikiwijs.nl/zoekopdracht/5004683">Eigenschappen van stoffen en materialen (D1)</a>',
      },
      percentageGoed: 0.75,
      percentageGoedPopulatieLaag: 0.31,
      percentageGoedPopulatieHoog: 0.73,
      volledigBeantwoord: true,
      voldoendeScorepunten: true,
    },
    {
      domein: {
        titel: 'Aarde en heelal (E)',
        titelHtml:
          '<a  target="_blank" rel="noreferrer"  href="https://zoeken.wikiwijs.nl/zoekopdracht/5004749">Aarde en heelal (E)</a>',
      },
      percentageGoed: 0.83,
      percentageGoedPopulatieLaag: 0.19,
      percentageGoedPopulatieHoog: 0.7,
      volledigBeantwoord: true,
      voldoendeScorepunten: false,
    },
    {
      domein: {
        titel: 'Gebruik van elektriciteit (G1)',
        titelHtml:
          '<a  target="_blank" rel="noreferrer"  href="https://zoeken.wikiwijs.nl/zoekopdracht/5004752">Gebruik van elektriciteit (G1)</a>',
      },
      percentageGoed: 0.82,
      percentageGoedPopulatieLaag: 0.46,
      percentageGoedPopulatieHoog: 0.8,
      volledigBeantwoord: true,
      voldoendeScorepunten: true,
    },
  ],
} as ExamenReport;
export const examen = {
  examenId: 17149,
  tijdvak: 1,
  opleidingsniveau: 1,
  leerweg: null,
  vakcode: '1023',
  nTerm: 0,
  vaknaam: 'natuurkunde',
  isPilot: false,
  jaar: 2017,
  opgavenboekje: 'https://www2.cito.nl/vo/ex2017/HA-1023-a-17-1-o.pdf',
  aantalItems: 28,
  correctievoorschrift: 'https://www2.cito.nl/vo/ex2017/HA-1023-a-17-1-c.pdf',
  uitwerkbijlage: 'https://www2.cito.nl/vo/ex2017/HA-1023-a-17-1-u.pdf',
  tekstboekje: '',
  opgaven: [
    {
      titel: 'Elektrische doorstroomverwarmer',
      items: [
        {
          code: 7173,
          titel: null,
          volgnummer: 1,
          maxscore: 1,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Energieomzettingen (C2)'],
        },
        {
          code: 7174,
          titel: null,
          volgnummer: 2,
          maxscore: 2,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: [
            'Energieomzettingen (C2)',
            'Gebruik van elektriciteit (G1)',
          ],
        },
        {
          code: +'7175',
          titel: null,
          volgnummer: 3,
          maxscore: 3,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Gebruik van elektriciteit (G1)'],
        },
        {
          code: +'7176',
          titel: null,
          volgnummer: 4,
          maxscore: 2,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Gebruik van elektriciteit (G1)'],
        },
        {
          code: +'7177',
          titel: null,
          volgnummer: 5,
          maxscore: 1,
          sleutel: 'A',
          aantalAlternatieven: 4,
          calamiteit: false,
          domeinen: ['Eigenschappen van stoffen en materialen (D1)'],
        },
        {
          code: +'7178',
          titel: null,
          volgnummer: 6,
          maxscore: 4,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Gebruik van elektriciteit (G1)'],
        },
      ],
    },
    {
      titel: 'Molybdeen-99',
      items: [
        {
          code: +'7179',
          titel: null,
          volgnummer: 7,
          maxscore: 3,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Medische beeldvorming (B2)'],
        },
        {
          code: +'7180',
          titel: null,
          volgnummer: 8,
          maxscore: 1,
          sleutel: 'A',
          aantalAlternatieven: 4,
          calamiteit: false,
          domeinen: ['Medische beeldvorming (B2)'],
        },
        {
          code: +'7181',
          titel: null,
          volgnummer: 9,
          maxscore: 4,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Medische beeldvorming (B2)'],
        },
        {
          code: '7182',
          titel: null,
          volgnummer: 10,
          maxscore: 4,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Medische beeldvorming (B2)'],
        },
        {
          code: '7183',
          titel: null,
          volgnummer: 11,
          maxscore: 1,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Medische beeldvorming (B2)'],
        },
        {
          code: '7184',
          titel: null,
          volgnummer: 12,
          maxscore: 3,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Medische beeldvorming (B2)'],
        },
      ],
    },
    {
      titel: 'Road-train',
      items: [
        {
          code: '7185',
          titel: null,
          volgnummer: 13,
          maxscore: 3,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Kracht en beweging (C1)'],
        },
        {
          code: '7186',
          titel: null,
          volgnummer: 14,
          maxscore: 4,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Energieomzettingen (C2)'],
        },
        {
          code: '7187',
          titel: null,
          volgnummer: 15,
          maxscore: 2,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Kracht en beweging (C1)'],
        },
        {
          code: '7188',
          titel: null,
          volgnummer: 16,
          maxscore: 4,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Energieomzettingen (C2)'],
        },
        {
          code: '7189',
          titel: null,
          volgnummer: 17,
          maxscore: 3,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Kracht en beweging (C1)'],
        },
      ],
    },
    {
      titel: 'Metaalmoeheid',
      items: [
        {
          code: '7190',
          titel: null,
          volgnummer: 18,
          maxscore: 3,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Eigenschappen van stoffen en materialen (D1)'],
        },
        {
          code: '7191',
          titel: null,
          volgnummer: 19,
          maxscore: 2,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Eigenschappen van stoffen en materialen (D1)'],
        },
        {
          code: '7192',
          titel: null,
          volgnummer: 20,
          maxscore: 2,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Informatieoverdracht (B1)'],
        },
        {
          code: '7193',
          titel: null,
          volgnummer: 21,
          maxscore: 4,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: [
            'Informatieoverdracht (B1)',
            'Eigenschappen van stoffen en materialen (D1)',
          ],
        },
        {
          code: '7194',
          titel: null,
          volgnummer: 22,
          maxscore: 3,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: [
            'Kracht en beweging (C1)',
            'Eigenschappen van stoffen en materialen (D1)',
          ],
        },
      ],
    },
    {
      titel: 'Naaldjes rond de aarde',
      items: [
        {
          code: '7195',
          titel: null,
          volgnummer: 23,
          maxscore: 3,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Eigenschappen van stoffen en materialen (D1)'],
        },
        {
          code: '7196',
          titel: null,
          volgnummer: 24,
          maxscore: 3,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Informatieoverdracht (B1)'],
        },
        {
          code: '7197',
          titel: null,
          volgnummer: 25,
          maxscore: 2,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Informatieoverdracht (B1)'],
        },
        {
          code: '7198',
          titel: null,
          volgnummer: 26,
          maxscore: 4,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Aarde en heelal (E)'],
        },
        {
          code: '7199',
          titel: null,
          volgnummer: 27,
          maxscore: 2,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: ['Aarde en heelal (E)'],
        },
        {
          code: '7200',
          titel: null,
          volgnummer: 28,
          maxscore: 3,
          sleutel: '',
          aantalAlternatieven: 0,
          calamiteit: false,
          domeinen: [],
        },
      ],
    },
  ],
  domeinen: [
    {
      titel: 'Informatieoverdracht (B1)',
      titelHtml:
        '<a  target="_blank" rel="noreferrer"  href="https://zoeken.wikiwijs.nl/zoekopdracht/5004560">Informatieoverdracht (B1)</a>',
    },
    {
      titel: 'Medische beeldvorming (B2)',
      titelHtml:
        '<a  target="_blank" rel="noreferrer"  href="https://zoeken.wikiwijs.nl/zoekopdracht/5004561">Medische beeldvorming (B2)</a>',
    },
    {
      titel: 'Kracht en beweging (C1)',
      titelHtml:
        '<a  target="_blank" rel="noreferrer"  href="https://zoeken.wikiwijs.nl/zoekopdracht/5004563">Kracht en beweging (C1)</a>',
    },
    {
      titel: 'Energieomzettingen (C2)',
      titelHtml:
        '<a  target="_blank" rel="noreferrer"  href="https://zoeken.wikiwijs.nl/zoekopdracht/5004757">Energieomzettingen (C2)</a>',
    },
    {
      titel: 'Eigenschappen van stoffen en materialen (D1)',
      titelHtml:
        '<a  target="_blank" rel="noreferrer"  href="https://zoeken.wikiwijs.nl/zoekopdracht/5004683">Eigenschappen van stoffen en materialen (D1)</a>',
    },
    {
      titel: 'Aarde en heelal (E)',
      titelHtml:
        '<a  target="_blank" rel="noreferrer"  href="https://zoeken.wikiwijs.nl/zoekopdracht/5004749">Aarde en heelal (E)</a>',
    },
    {
      titel: 'Gebruik van elektriciteit (G1)',
      titelHtml:
        '<a  target="_blank" rel="noreferrer"  href="https://zoeken.wikiwijs.nl/zoekopdracht/5004752">Gebruik van elektriciteit (G1)</a>',
    },
  ],
  id: '5019f8f4-2a51-4da9-92c0-9a709c0d175f',
  createdByUserId: '00000000-0000-0000-0000-000000000000',
  created: '2021-03-06T21:34:58.651Z',
  lastModified: '2021-03-06T21:36:20.263Z',
  lastModifiedByUserId: '00000000-0000-0000-0000-000000000000',
  isDeleted: false,
} as Examen;
export const vaknaam = 'natuurkunde';
export const niveau = 'HAVO';
